kind: PersistentVolume
apiVersion: v1
metadata:
  name: subjob-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kubegenetest/subjob
    type: Directory
