kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: subjob-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: subjob-pv
  resources:
    requests:
      storage: 1Gi
