kind: PersistentVolume
apiVersion: v1
metadata:
  name: gcs-data
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /xsw/kubegenetest/data/
    type: Directory
