kind: PersistentVolume
apiVersion: v1
metadata:
  name: gcs-tmp-result
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kubegenetest/tmpres/
    type: Directory
