kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-dag-role
subjects:
  - kind: ServiceAccount
    name: kube-dag
    # replace with non-default namespace name
    namespace: default
roleRef:
  kind: ClusterRole
  name: kube-dag
  apiGroup: rbac.authorization.k8s.io