#
#       A   E
#      / \ /
#     B   C
#    /    \
#   D      F

apiVersion: execution.kubegene.io/v1alpha1
kind: Execution
metadata:
  name: exec-2
spec:
  tasks:
  - commandSet:
    - echo A >> /tmp/execution/exec-2.txt
    image: ubuntu
    name: a
    type: Job
    volumes:
      volumea:
        mountFrom:
          pvc: execution-pvc
        mountPath: /tmp/execution
  - commandSet:
    - echo B >> /tmp/execution/exec-2.txt
    dependents:
    - target: a
      type: whole
    image: ubuntu
    name: b
    type: Job
    volumes:
      volumeb:
        mountFrom:
          pvc: execution-pvc
        mountPath: /tmp/execution
  - commandSet:
    - echo C >> /tmp/execution/exec-2.txt
    dependents:
    - target: a
      type: whole
    - target: e
      type: whole
    image: ubuntu
    name: c
    type: Job
    volumes:
      volumec:
        mountFrom:
          pvc: execution-pvc
        mountPath: /tmp/execution
  - commandSet:
    - echo D >> /tmp/execution/exec-2.txt
    dependents:
    - target: b
      type: whole
    image: ubuntu
    name: d
    type: Job
    volumes:
      volumed:
        mountFrom:
          pvc: execution-pvc
        mountPath: /tmp/execution
  - commandSet:
    - echo E >> /tmp/execution/exec-2.txt
    dependents: null
    image: ubuntu
    name: e
    type: Job
    volumes:
      volumee:
        mountFrom:
          pvc: execution-pvc
        mountPath: /tmp/execution
  - commandSet:
    - echo F >> /tmp/execution/exec-2.txt
    dependents:
    - target: c
      type: whole
    image: ubuntu
    name: f
    type: Job
    volumes:
      volumef:
        mountFrom:
          pvc: execution-pvc
        mountPath: /tmp/execution