kind: PersistentVolume
apiVersion: v1
metadata:
  name: execution-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/execution/
    type: DirectoryOrCreate
