kind: PersistentVolume
apiVersion: v1
metadata:
  name: subrepjob-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/subrepjob
    type: DirectoryOrCreate
