kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: subrepjob-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: subrepjob-pv
  resources:
    requests:
      storage: 1Gi
