#
#       A   E     G
#      / \ /     / \
#     B   C     H  I
#    /    \     \ /
#   D      F     J

apiVersion: execution.kubegene.io/v1alpha1
kind: Execution
metadata:
  creationTimestamp: null
  name: simple-example
spec:
  tasks:
  - commands:
    - echo A >> /tmp/hostvolume/test.txt
    dependents: null
    image: ubuntu
    name: a
    type: Job
    volumes:
      volumea:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo B >> /tmp/hostvolume/test.txt
    dependents:
    - target: a
      type: whole
    image: ubuntu
    name: b
    type: Job
    volumes:
      volumeb:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo C >> /tmp/hostvolume/test.txt
    dependents:
    - target: a
      type: whole
    - target: e
      type: whole
    image: ubuntu
    name: c
    type: Job
    volumes:
      volumec:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo D >> /tmp/hostvolume/test.txt
    dependents:
    - target: b
      type: whole
    image: ubuntu
    name: d
    type: Job
    volumes:
      volumed:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo E >> /tmp/hostvolume/test.txt
    dependents: null
    image: ubuntu
    name: e
    type: Job
    volumes:
      volumee:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo F >> /tmp/hostvolume/test.txt
    dependents:
    - target: c
      type: whole
    image: ubuntu
    name: f
    type: Job
    volumes:
      volumef:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo G >> /tmp/hostvolume/test.txt
    dependents:
    image: ubuntu
    name: g
    type: Job
    volumes:
      volumeg:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo H >> /tmp/hostvolume/test.txt
    dependents:
    - target: g
      type: whole
    image: ubuntu
    name: h
    type: Job
    volumes:
      volumeh:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo I >> /tmp/hostvolume/test.txt
    dependents:
    - target: g
      type: whole
    image: ubuntu
    name: i
    type: Job
    volumes:
      volumei:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo J >> /tmp/hostvolume/test.txt
    dependents:
    - target: h
      type: whole
    - target: i
      type: whole
    image: ubuntu
    name: j
    type: Job
    volumes:
      volumej:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume