#
#       A   E
#      / \ /
#     B   C
#    /    \
#   D      F

apiVersion: execution.kubegene.io/v1alpha1
kind: Execution
metadata:
  creationTimestamp: null
  name: simple-example
spec:
  tasks:
  - commandSet:
    - echo A >> /tmp/hostvolume/test.txt
    dependents: null
    image: ubuntu
    name: a
    type: Job
    volumes:
      volumea:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commandSet:
    - echo B >> /tmp/hostvolume/test.txt
    dependents:
    - target: a
      type: whole
    image: ubuntu
    name: b
    type: Job
    volumes:
      volumeb:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commandSet:
    - echo C >> /tmp/hostvolume/test.txt
    dependents:
    - target: a
      type: whole
    - target: e
      type: whole
    image: ubuntu
    name: c
    type: Job
    volumes:
      volumec:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commandSet:
    - echo D >> /tmp/hostvolume/test.txt
    dependents:
    - target: b
      type: whole
    image: ubuntu
    name: d
    type: Job
    volumes:
      volumed:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commandSet:
    - echo E >> /tmp/hostvolume/test.txt
    dependents: null
    image: ubuntu
    name: e
    type: Job
    volumes:
      volumee:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commandSet:
    - echo F >> /tmp/hostvolume/test.txt
    dependents:
    - target: c
      type: whole
    image: ubuntu
    name: f
    type: Job
    volumes:
      volumef:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume