#
#       A
#      / \
#     B   C
#    /
#   D

apiVersion: execution.kubegene.io/v1alpha1
kind: Execution
metadata:
  creationTimestamp: null
  name: simple-example
spec:
  tasks:
  - commands:
    - echo A >> /tmp/hostvolume/test.txt
    dependents: null
    image: ubuntu
    name: a
    type: Job
    volumes:
      volumea:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo B >> /tmp/hostvolume/test.txt
    dependents:
    - target: a
      type: whole
    image: ubuntu
    name: b
    type: Job
    volumes:
      volumeb:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo C >> /tmp/hostvolume/test.txt
    dependents:
    - target: a
      type: whole
    image: ubuntu
    name: c
    type: Job
    volumes:
      volumec:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
  - commands:
    - echo D >> /tmp/hostvolume/test.txt
    dependents:
    - target: b
      type: whole
    image: ubuntu
    name: d
    type: Job
    volumes:
      volumed:
        mountFrom:
          pvc: test-host-path
        mountPath: /tmp/hostvolume
